title: Hello, world! I'm Park Hyunah.
description: > # this means to ignore newlines until "baseurl:"
  I'm learning Computer Science in Ewha Womans University. This is my academic blog.
permalink: ':title/'
baseurl: "/flexible-jekyll" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Park Hyunah # add your name
author-img: "https://github.com/hak2711/hak2711.github.io/blob/master/04/20200424_043400175_iOS.jpg?raw=true" # add your photo
about-author: I want to be a developer. Always find new things to learn. # add description
social-twitter: # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: artemsheludko # add your Github handle
social-linkedin: # add your Linkedin handle
social-email: # add your Email address

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
